name: CI Workflow
on:
  pull_request:
jobs:
  gen-check:
    runs-on: ubuntu-18.04
    name: Gen check
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run gen-check
        run: |
          make gen-check
  lint:
    runs-on: ubuntu-18.04
    name: Lint
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Markdownlint
        run: |
          npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint
        run: |
          make lint
  build:
    name: Compile
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # We need to guess version via git tags.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: compile
        run: make build
  test:
    name: Unit test
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: make test
        run: make test
