name: CI Workflow
on:
  pull_request:
jobs:
  gen-check:
    runs-on: ubuntu-22.04
    name: Gen check
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run gen-check
        run: |
          make gen-check
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Markdownlint
        run: |
          npm install -g markdownlint-cli
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run lint
        run: |
          make lint
  build:
    name: Compile
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # We need to guess version via git tags.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: compile
        run: make build
      - name: docker build
        run: make docker
  licenses-lint:
    name: Licenses Lint
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: generate license mirror
        run: make mirror-licenses
      - name: lint-licenses
        run: make lint-licenses
  test:
    name: Unit test
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: make test
        run: make test
